steps:
  - task: AzureCLI@2
    name: set_variables
    displayName: Set credentials
    inputs:
      azureSubscription: "$(azureSubscription)"
      addSpnToEnvironment: true
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
        Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$env:idToken"
        Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
        Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
        Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
