steps:
  - script: |
      echo "Configuring Git authentication..."
      git config --global http.https://<PATH>.extraheader "Authorization: Basic $(GIT_TOKEN)"  # TODO: Replace <PATH> with the URL of your Git repository
    displayName: "Configure Git Authentication"
