parameters:
  - name: stageName
    type: string
  - name: action
    type: string
    default: "plan"

stages:
  - stage: ${{ parameters.stageName }}
    displayName: "Terragrunt ${{ parameters.action }}"
    jobs:
      - job: TerragruntJob
        displayName: "Terragrunt ${{ parameters.action }}"
        variables:
          - template: config.yaml
        steps:
          - checkout: self
            persistCredentials: "true"
            fetchDepth: "0"

          - template: install-terraform.yaml
          - template: install-terragrunt.yaml
          - template: configure-azure.yaml
          - template: configure-git.yaml

          - script: |
              terragrunt run-all validate \
                --terragrunt-non-interactive \
                --terragrunt-provider-cache \
                --terragrunt-working-dir $(WORKING_DIR)
            displayName: "Validate Terraform configuration"

          - script: |
              terragrunt run-all ${{ parameters.action }} \
                -compact-warnings \
                --terragrunt-non-interactive \
                --terragrunt-provider-cache \
                --terragrunt-working-dir $(WORKING_DIR)
            displayName: "Run Terragrunt ${{ parameters.action }}"
